# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    default_locale: fr
    secret: '%env(APP_SECRET)%'
    csrf_protection: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    session:
        handler_id: 'app.redis.session_handler'
        cookie_secure: auto
        cookie_samesite: lax

    #esi: true
    #fragments: true
    php_errors:
        log: true
