framework:
    messenger:
        # Send failed messages to this transport for later handling.
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            failed: 'doctrine://default?queue_name=failed'
            sync: 'sync://'
            async:
                dsn: '%env(RABBITMQ_URL)%/%2f/messages'
                retry_strategy:
                    # Retry after 1 second, 2 seconds, 4 seconds, 8 seconds
                    max_retries: 4
                    delay: 1000
                    multiplier: 2

        routing:
            'Symfony\Component\Mailer\Messenger\SendEmailMessage': async
