version: '3'

services:
    database:
        image: postgres:13
        ports: [5432]
        environment:
            POSTGRES_USER: main
            POSTGRES_PASSWORD: main
            POSTGRES_DB: main

    redis:
        image: redis:6-alpine
        ports: [6379]

    rabbitmq:
        image: rabbitmq:3.8-management-alpine
        ports: [5672, 15672]
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest

    mailer:
        image: schickling/mailcatcher
        ports: [1025, 1080]
