name: CI

on: push

jobs:
    php-cs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Install PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '7.4'
                  coverage: none
            - name: Install php-cs-fixer
              run: wget https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v2.16.4/php-cs-fixer.phar -q
            - name: Check coding style
              run: php php-cs-fixer.phar fix --dry-run --diff

    prettier:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Install prettier
              run: yarn global add prettier@2.2.1
            - name: Check coding style
              run: ~/.yarn/bin/prettier --check assets --config .prettierrc.json
